import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';
import {
  brandColors,
  semanticColors,
  neutralColors,
  medicalAlertColors,
  aiDiagnosisColors,
  ecommerceColors,
  appointmentColors,
  gradients,
  shadows,
} from './colors';
import { typography, spacing, borderRadius } from './dimensions';

// Light Theme
export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: brandColors.primary.main,
    primaryContainer: brandColors.primary.light,
    onPrimary: brandColors.primary.contrast,
    secondary: brandColors.secondary.main,
    secondaryContainer: brandColors.secondary.light,
    onSecondary: brandColors.secondary.contrast,
    tertiary: brandColors.accent.main,
    tertiaryContainer: brandColors.accent.light,
    onTertiary: brandColors.accent.contrast,
    error: semanticColors.error.main,
    errorContainer: semanticColors.error.background,
    onError: semanticColors.error.contrast,
    background: neutralColors.white,
    onBackground: neutralColors.gray[900],
    surface: neutralColors.white,
    surfaceVariant: neutralColors.gray[100],
    onSurface: neutralColors.gray[900],
    onSurfaceVariant: neutralColors.gray[700],
    outline: neutralColors.gray[300],
    outlineVariant: neutralColors.gray[200],
    inverseSurface: neutralColors.gray[900],
    inverseOnSurface: neutralColors.white,
    inversePrimary: brandColors.primary.light,
    shadow: '#000000',
    scrim: 'rgba(0, 0, 0, 0.3)',
    // Custom colors
    success: semanticColors.success.main,
    successContainer: semanticColors.success.background,
    onSuccess: semanticColors.success.contrast,
    warning: semanticColors.warning.main,
    warningContainer: semanticColors.warning.background,
    onWarning: semanticColors.warning.contrast,
    info: semanticColors.info.main,
    infoContainer: semanticColors.info.background,
    onInfo: semanticColors.info.contrast,
  },
  // Custom properties
  brand: brandColors,
  semantic: semanticColors,
  neutral: neutralColors,
  medicalAlert: medicalAlertColors,
  aiDiagnosis: aiDiagnosisColors,
  ecommerce: ecommerceColors,
  appointment: appointmentColors,
  gradients,
  shadows,
  typography,
  spacing,
  borderRadius,
};

// Dark Theme
export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: brandColors.primary.light,
    primaryContainer: brandColors.primary.dark,
    onPrimary: '#000000',
    secondary: brandColors.secondary.light,
    secondaryContainer: brandColors.secondary.dark,
    onSecondary: '#000000',
    tertiary: brandColors.accent.light,
    tertiaryContainer: brandColors.accent.dark,
    onTertiary: '#000000',
    error: semanticColors.error.light,
    errorContainer: semanticColors.error.dark,
    onError: '#000000',
    background: '#121212',
    onBackground: '#FFFFFF',
    surface: '#1E1E1E',
    surfaceVariant: '#2C2C2C',
    onSurface: '#FFFFFF',
    onSurfaceVariant: '#B0B0B0',
    outline: '#6E6E6E',
    outlineVariant: '#383838',
    inverseSurface: '#FFFFFF',
    inverseOnSurface: '#121212',
    inversePrimary: brandColors.primary.main,
    shadow: '#000000',
    scrim: 'rgba(0, 0, 0, 0.5)',
    // Custom colors
    success: semanticColors.success.light,
    successContainer: semanticColors.success.dark,
    onSuccess: '#000000',
    warning: semanticColors.warning.light,
    warningContainer: semanticColors.warning.dark,
    onWarning: '#000000',
    info: semanticColors.info.light,
    infoContainer: semanticColors.info.dark,
    onInfo: '#000000',
  },
  // Custom properties
  brand: brandColors,
  semantic: semanticColors,
  neutral: neutralColors,
  medicalAlert: medicalAlertColors,
  aiDiagnosis: aiDiagnosisColors,
  ecommerce: ecommerceColors,
  appointment: appointmentColors,
  gradients,
  shadows,
  typography,
  spacing,
  borderRadius,
};
