-- File: backend/migrations/036_harden_otp.sql

ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "purpose" VARCHAR(50) NOT NULL DEFAULT 'login';
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "resend_count" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "max_attempts" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "cooldown_until" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "locked_until" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "last_sent_at" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "last_request_ip_hash" VARCHAR(128);
ALTER TABLE "OTPVerification" ADD COLUMN IF NOT EXISTS "verified_at" TIMESTAMP WITH TIME ZONE;
