import PDFDocument from 'pdfkit';
import { buildRadiographSectionLabels } from './xCoreAnalysisCaseDomain.js';

function ensureSpace(doc, needed) {
  if (doc.y + needed > doc.page.height - doc.page.margins.bottom) doc.addPage();
}

function writeWrapped(doc, label, value) {
  doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
  doc.font('Helvetica').text(value || '-');
}

export async function buildXCoreAnalysisPdf({ snapshot, imageBuffers }) {
  const doc = new PDFDocument({ size: 'A4', margin: 42, compress: true, info: { Title: snapshot.title || 'X-Core Analysis' } });
  const chunks = [];
  doc.on('data', (chunk) => chunks.push(chunk));
  const complete = new Promise((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  doc.fontSize(20).font('Helvetica-Bold').text('Laporan Analisis X-Core');
  doc.moveDown(0.3).fontSize(9).font('Helvetica').fillColor('#475569');
  doc.text(`Kasus ${snapshot.id} • Versi ${snapshot.report_version} • ${snapshot.generated_at}`);
  doc.fillColor('#111827').moveDown();
  writeWrapped(doc, 'Pasien', snapshot.patient?.name || snapshot.patient_id);
  writeWrapped(doc, 'Pembuat analisis', snapshot.creator?.name || snapshot.created_by);
  writeWrapped(doc, 'Judul', snapshot.title);

  doc.moveDown().fontSize(14).font('Helvetica-Bold').text('Data klinis');
  doc.fontSize(10).font('Helvetica');
  const clinicalEntries = Object.entries(snapshot.clinical_data || {});
  if (!clinicalEntries.length) doc.text('Tidak ada data klinis yang dicatat.');
  clinicalEntries.forEach(([key, value]) => writeWrapped(doc, key.replaceAll('_', ' '), Array.isArray(value) ? value.join(', ') : String(value || '-')));

  const orderedItems = [...snapshot.items].sort((a, b) => a.display_order - b.display_order);
  const labels = buildRadiographSectionLabels(orderedItems);
  orderedItems.forEach((item, index) => {
    doc.addPage();
    doc.fontSize(15).font('Helvetica-Bold').fillColor('#0f172a').text(labels[index]);
    if (item.title && item.title !== labels[index]) doc.fontSize(9).font('Helvetica').fillColor('#64748b').text(item.title);
    doc.moveDown(0.5);
    const image = imageBuffers.get(item.id);
    if (image) {
      const maxWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
      const maxHeight = item.radiograph_type === 'PANORAMIC' ? 350 : 430;
      doc.image(image, { fit: [maxWidth, maxHeight], align: 'center', valign: 'center' });
      doc.moveDown(0.8);
    } else {
      doc.font('Helvetica-Oblique').text('Render citra tidak tersedia.');
    }
    ensureSpace(doc, 120);
    doc.fontSize(11).font('Helvetica-Bold').text('Temuan');
    doc.fontSize(10).font('Helvetica').text(item.findings || 'Tidak ada temuan yang dicatat.');
    doc.moveDown(0.6).fontSize(11).font('Helvetica-Bold').text('Pengukuran');
    doc.fontSize(9).font('Helvetica');
    if (!item.measurements?.length) doc.text('Tidak ada pengukuran.');
    item.measurements?.forEach((measurement) => doc.text(`• ${measurement.label || measurement.metadata?.label || 'Pengukuran'}: ${measurement.metadata?.value_label || measurement.label || '-'}`));
  });

  doc.addPage();
  doc.fontSize(15).font('Helvetica-Bold').text('Kesimpulan Analisis');
  doc.moveDown(0.4).fontSize(10).font('Helvetica').text(snapshot.conclusion || 'Tidak ada kesimpulan yang dicatat.');
  doc.moveDown(2).fontSize(8).fillColor('#64748b');
  doc.text(`Report ID: ${snapshot.report_id}`);
  doc.text(`Case ID: ${snapshot.id}`);
  doc.text(`Version: ${snapshot.report_version}`);
  doc.text(`Generated by: ${snapshot.created_by}`);
  doc.text(`Snapshot timestamp: ${snapshot.generated_at}`);
  doc.end();
  return complete;
}

