const ROLE_NOTIFICATIONS = [
  {
    id: 'CLN-OWNER-001',
    roles: ['owner', 'manager', 'clinic_admin'],
    category: 'billing',
    title: 'Revenue dip detected on Bandung branch',
    description: 'Week-to-date revenue -8.4% vs target. Hygiene line underperforming.',
    timeframe: 'Today',
    timestamp: '09:20 WIB',
    tag: 'Revenue',
    meta: 'Owner dashboard • Branch Bandung',
    severity: 'medium',
    actions: [{ label: 'View Branch KPI', href: '/clinic-portal/reports' }],
    read: false,
  },
  {
    id: 'CLN-OWNER-002',
    roles: ['owner', 'manager'],
    category: 'operations',
    title: 'Multi-branch supply reorder awaiting approval',
    description: 'Four branches requested nano-etch kits. Bulk discount expires in 6 hours.',
    timeframe: 'Today',
    timestamp: '08:40 WIB',
    tag: 'Procurement',
    meta: 'Inventory Board • Supplier Mitra Farma',
    severity: 'high',
    actions: [{ label: 'Review Purchase', href: '/clinic-portal/inventory' }],
    read: false,
  },
  {
    id: 'CLN-MANAGER-001',
    roles: ['manager', 'clinic_admin'],
    category: 'patient',
    title: 'VIP patient follow-up missing assignment',
    description: 'Patient Dahlia P. waiting 2 days for aligner consult scheduling.',
    timeframe: 'Today',
    timestamp: '09:05 WIB',
    tag: 'Customer Success',
    meta: 'CRM Task • Priority high',
    severity: 'medium',
    actions: [{ label: 'Assign Staff', href: '/clinic-portal/patients' }],
    read: false,
  },
  {
    id: 'CLN-FRONT-001',
    roles: ['front_office', 'staff'],
    category: 'schedule',
    title: 'Walk-in ortho queue nearing SLA',
    description: 'Queue #108 reached 22 minutes wait. Auto SMS reminder triggered.',
    timeframe: 'Today',
    timestamp: '08:55 WIB',
    tag: 'Queue Load',
    meta: 'Lobby Queue • 6 waiting',
    severity: 'medium',
    actions: [{ label: 'Open Queue', href: '/clinic-portal/schedule' }],
    read: false,
  },
  {
    id: 'CLN-FRONT-002',
    roles: ['front_office', 'staff'],
    category: 'schedule',
    title: 'Patient rescheduled via WhatsApp',
    description: 'Risa D. moved veneer consult to 15:45. Update doctor briefing notes.',
    timeframe: 'Today',
    timestamp: '08:20 WIB',
    tag: 'Schedule',
    meta: 'Auto-sync from WA Bot',
    severity: 'low',
    actions: [{ label: 'Review Schedule', href: '/clinic-portal/schedule' }],
    read: true,
  },
  {
    id: 'CLN-NURSE-001',
    roles: ['nurse', 'staff'],
    category: 'operations',
    title: 'Sterilization cassette B idle for 35 minutes',
    description: 'Surgical kit pending since 07:45. Compliance requires logging ASAP.',
    timeframe: 'Today',
    timestamp: '08:30 WIB',
    tag: 'Sterilization',
    meta: 'Central Steri • Nurse Kevin',
    severity: 'high',
    actions: [{ label: 'Start Cycle', href: '/clinic-portal/inventory' }],
    read: false,
  },
  {
    id: 'CLN-CASHIER-001',
    roles: ['cashier'],
    category: 'billing',
    title: 'BPJS claim needs clarification',
    description: 'Case #INS-88312 missing X-ray attachment. Deadline 17:00 today.',
    timeframe: 'Today',
    timestamp: '08:10 WIB',
    tag: 'Insurance',
    meta: 'Cashier Desk • Batch 14',
    severity: 'high',
    actions: [{ label: 'Fix Claim', href: '/clinic-portal/billing' }],
    read: false,
  },
  {
    id: 'CLN-ALL-001',
    roles: ['all'],
    category: 'marketing',
    title: 'New public review published',
    description: 'Patient Maya K. rated 5/5 but noted Saturday queue stretch.',
    timeframe: 'Last 7 Days',
    timestamp: '13 Jan · 16:45 WIB',
    tag: 'Experience',
    meta: 'Google Profile • Branch Bandung',
    severity: 'low',
    actions: [{ label: 'Respond', href: '/clinic-portal/public-profile' }],
    read: true,
  },
];

export const getClinicNotificationsForRoles = (roles = [], options = {}) => {
  const normalizedRoles = roles.length ? roles : ['staff'];
  if (options.includeAll) return ROLE_NOTIFICATIONS;
  return ROLE_NOTIFICATIONS.filter((item) => {
    if (item.roles.includes('all')) return true;
    return item.roles.some((role) => normalizedRoles.includes(role));
  });
};
