const ADMIN_NOTIFICATIONS = [
  {
    id: 'ADM-001',
    roles: ['super_admin', 'customer_success_manager', 'business_manager'],
    category: 'network',
    title: 'Clinic onboarding pending final verification',
    description: 'BrightSmile Dental Bandung submitted legal documents 55 minutes ago. SLA for approval is 6 hours.',
    timeframe: 'Today',
    timestamp: '09:24 WIB',
    tag: 'Onboarding',
    meta: 'Stage 3 • CS Owner: Lia',
    severity: 'high',
    actions: [{ label: 'Review Application', href: '/admin/clinic-management/verification' }],
    read: false,
  },
  {
    id: 'ADM-002',
    roles: ['super_admin', 'finance_manager', 'business_manager'],
    category: 'billing',
    title: 'Payout reconciliation mismatch detected',
    description: 'Rp 47.5M discrepancy for multi-branch clinics in the 15 Jan payout window.',
    timeframe: 'Today',
    timestamp: '08:41 WIB',
    tag: 'Finance Alert',
    meta: 'Batch #RV-2024-015 • Impact medium',
    severity: 'high',
    actions: [{ label: 'Open Reconciliation', href: '/admin/revenue-billing/payments' }],
    read: false,
  },
  {
    id: 'ADM-003',
    roles: ['super_admin', 'platform_manager', 'ai_engineer'],
    category: 'ai',
    title: 'AI usage spike on segmentation model',
    description: 'Clinic-owned dentists increased AI diagnostic scans by 38% in the past 2 hours.',
    timeframe: 'Today',
    timestamp: '07:55 WIB',
    tag: 'Model Monitoring',
    meta: 'Model: Radiant-3.2 • GPU 76% util.',
    severity: 'medium',
    actions: [{ label: 'Inspect Usage', href: '/admin/ai-platform' }],
    read: true,
  },
  {
    id: 'ADM-004',
    roles: ['super_admin', 'technical_support', 'customer_success_manager'],
    category: 'support',
    title: 'High priority ticket approaching SLA breach',
    description: 'Clinic Sehat Gigi reported teleconsult routing outage. SLA breach in 42 minutes.',
    timeframe: 'Today',
    timestamp: '07:12 WIB',
    tag: 'SLA Risk',
    meta: 'Ticket #SUP-8821 • CS Owner: Nasha',
    severity: 'high',
    actions: [{ label: 'Open Ticket', href: '/admin/support-helpdesk' }],
    read: false,
  },
  {
    id: 'ADM-005',
    roles: ['super_admin', 'compliance_officer'],
    category: 'compliance',
    title: 'DPA renewal needed for 4 dental groups',
    description: 'Data Processing Agreement for region West Java expires in 5 days. Draft update ready.',
    timeframe: 'Last 7 Days',
    timestamp: '13 Jan · 16:08 WIB',
    tag: 'Regulatory',
    meta: 'Owner: Compliance • Status: Drafted',
    severity: 'medium',
    actions: [{ label: 'Review Draft', href: '/admin/compliance-security/regulatory' }],
    read: false,
  },
  {
    id: 'ADM-006',
    roles: ['super_admin', 'business_manager', 'platform_manager'],
    category: 'analytics',
    title: 'Revenue forecast dropped vs last week',
    description: 'Projected MRR is Rp 120M (-6.4%) due to muted clinic onboarding in Surabaya.',
    timeframe: 'Last 7 Days',
    timestamp: '12 Jan · 09:18 WIB',
    tag: 'Forecast',
    meta: 'Owner: BizOps • Scenario: Base',
    severity: 'medium',
    actions: [{ label: 'Open Report', href: '/admin/analytics-reporting' }],
    read: true,
  },
  {
    id: 'ADM-007',
    roles: ['super_admin', 'platform_manager'],
    category: 'partnership',
    title: 'API key rotation requested by insurer',
    description: 'Prudential Health requires new webhook secret for claim sync before 20 Jan.',
    timeframe: 'Earlier',
    timestamp: '10 Jan · 11:45 WIB',
    tag: 'Integration',
    meta: 'Owner: Platform • Status: Pending approval',
    severity: 'low',
    actions: [{ label: 'Manage Keys', href: '/admin/partnership/api' }],
    read: true,
  },
  {
    id: 'ADM-008',
    roles: ['all'],
    category: 'default',
    title: 'System maintenance scheduled',
    description: 'Platform upgrade on 18 Jan 00:00-02:00 WIB. Expect minor downtime.',
    timeframe: 'Earlier',
    timestamp: '09 Jan · 09:00 WIB',
    tag: 'System',
    meta: 'Platform Ops',
    severity: 'low',
    actions: [{ label: 'View Details', href: '/admin/system-administration/monitoring' }],
    read: true,
  },
];

export const getAdminNotificationsForRoles = (roles = [], options = {}) => {
  const normalizedRoles = roles.length ? roles : ['admin'];
  if (options.includeAll) return ADMIN_NOTIFICATIONS;
  return ADMIN_NOTIFICATIONS.filter((item) => {
    if (item.roles.includes('all')) return true;
    return item.roles.some((role) => normalizedRoles.includes(role));
  });
};
