import http from 'k6/http';
import { check, fail } from 'k6';

export const DEFAULT_BASE_URL = 'http://127.0.0.1:4000';
export const BASE_URL = (__ENV.BASE_URL || DEFAULT_BASE_URL).replace(/\/$/, '');
export const API_PREFIX = normalizePrefix(__ENV.API_PREFIX || '/v1');
export const API_URL = `${BASE_URL}${API_PREFIX}`;

export const PATIENT_EMAIL = __ENV.PATIENT_EMAIL || __ENV.TEST_EMAIL || 'adrianhhhalim@gmail.com';
export const DENTIST_EMAIL = __ENV.DENTIST_EMAIL || 'dentist10.clinic2@dentists.com';
export const PATIENT_PASSWORD = __ENV.PATIENT_PASSWORD || __ENV.TEST_PASSWORD || 'password123';
export const DENTIST_PASSWORD = __ENV.DENTIST_PASSWORD || __ENV.TEST_PASSWORD || 'password123';
export const DENTIST_PROFILE_ID = __ENV.DENTIST_PROFILE_ID || __ENV.DENTIST_ID || '365';
export const CLINIC_BRANCH_ID = __ENV.CLINIC_BRANCH_ID || '';
export const FIXTURE_APPOINTMENT_ID = __ENV.APPOINTMENT_ID || '';

function normalizePrefix(prefix) {
  if (!prefix) return '';
  const withLeadingSlash = prefix[0] === '/' ? prefix : `/${prefix}`;
  return withLeadingSlash.replace(/\/$/, '');
}

export function login(email, password, tagName) {
  return http.post(
    `${API_URL}/auth/login`,
    JSON.stringify({ email, password }),
    {
      headers: { 'Content-Type': 'application/json' },
      tags: { name: tagName, feature: 'login' },
    }
  );
}

export function extractAccessToken(res) {
  const body = safeJson(res);
  return body.accessToken || body.token || body.access_token || nested(body, ['data', 'accessToken']) || '';
}

export function createConfirmedFixtureAppointment({ patientToken, dentistToken, runSeed }) {
  const payload = buildAppointmentPayload({
    dentistProfileId: DENTIST_PROFILE_ID,
    clinicBranchId: CLINIC_BRANCH_ID,
    runSeed,
    vu: 0,
    iter: 0,
    reason: 'Fixture confirmed appointment untuk pengujian latency chat dan upload',
  });

  const createRes = http.post(`${API_URL}/appointments`, JSON.stringify(payload), {
    headers: jsonHeaders(patientToken),
    tags: { name: 'SETUP POST /appointments', feature: 'setup_create_fixture' },
  });

  check(createRes, {
    'setup create appointment status 201': (r) => r.status === 201,
  });

  if (createRes.status !== 201) {
    fail(`Setup gagal: tidak bisa membuat appointment fixture. Status=${createRes.status}, body=${createRes.body}`);
  }

  const createBody = safeJson(createRes);
  const appointmentId = nested(createBody, ['appointment', 'id']);
  if (!appointmentId) {
    fail(`Setup gagal: appointment.id tidak ditemukan. Body=${createRes.body}`);
  }

  const confirmRes = http.patch(`${API_URL}/appointments/${appointmentId}/confirm`, null, {
    headers: jsonHeaders(dentistToken),
    tags: { name: 'SETUP PATCH /appointments/:id/confirm', feature: 'setup_confirm_fixture' },
  });

  check(confirmRes, {
    'setup confirm appointment status 200': (r) => r.status === 200,
  });

  if (confirmRes.status !== 200) {
    fail(`Setup gagal: tidak bisa confirm appointment fixture ${appointmentId}. Status=${confirmRes.status}, body=${confirmRes.body}`);
  }

  return String(appointmentId);
}

export function warmUpCommunicationFixture({ patientToken, appointmentId }) {
  const headers = jsonHeaders(patientToken);
  const messageRes = http.post(
    `${API_URL}/communications/appointments/${appointmentId}/chat/messages`,
    JSON.stringify({
      message: `Warmup latency fixture ${Date.now()}`,
      messageType: 'text',
    }),
    {
      headers,
      tags: { name: 'SETUP POST /communications/appointments/:id/chat/messages', feature: 'setup_warmup_message' },
    }
  );

  check(messageRes, {
    'setup warmup message status 201': (r) => r.status === 201,
  });

  if (messageRes.status !== 201) {
    fail(`Setup gagal: warmup chat message untuk appointment ${appointmentId} gagal. Status=${messageRes.status}, body=${messageRes.body}`);
  }

  const listRes = http.get(`${API_URL}/communications/appointments/${appointmentId}/chat/messages?limit=5`, {
    headers,
    tags: { name: 'SETUP GET /communications/appointments/:id/chat/messages', feature: 'setup_warmup_messages_list' },
  });

  check(listRes, {
    'setup warmup messages list status 200': (r) => r.status === 200,
  });
}

export function buildAppointmentPayload({ dentistProfileId, clinicBranchId, runSeed, vu, iter, reason }) {
  const slotIndex = (runSeed * 45) + (vu * 10000 * 45) + (iter * 45);
  const start = new Date(Date.now() + (7 * 24 * 60 * 60 * 1000) + (slotIndex * 60 * 1000));
  const end = new Date(start.getTime() + (30 * 60 * 1000));
  const payload = {
    dentistId: String(dentistProfileId),
    start: start.toISOString(),
    end: end.toISOString(),
    appointmentType: 'virtual',
    reason,
    notes: 'Generated by k6 latency test',
    metadata: {
      source: 'k6_latency_test',
      vu,
      iter,
      runSeed,
    },
  };

  if (clinicBranchId) {
    payload.clinicBranchId = String(clinicBranchId);
  }

  return payload;
}

export function recordResult({ res, trend, failedRate, counter, validStatuses, checkName, underName }) {
  const isValid = validStatuses.indexOf(res.status) !== -1;
  trend.add(res.timings.duration);
  failedRate.add(!isValid);
  counter.add(1);

  const checks = {};
  checks[checkName] = () => isValid;
  checks[underName] = (r) => r.timings.duration < 2000;
  check(res, checks);
}

export function jsonHeaders(token) {
  return {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
  };
}

export function authOnlyHeaders(token) {
  return {
    Authorization: `Bearer ${token}`,
  };
}

export function safeJson(res) {
  try {
    return res.json();
  } catch (_) {
    return {};
  }
}

export function nested(value, path) {
  let current = value;
  for (let i = 0; i < path.length; i += 1) {
    if (!current || typeof current !== 'object') return undefined;
    current = current[path[i]];
  }
  return current;
}
